### ISSUE TITLE
Implement Single Sign-On (SSO) across all apps

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/dxp-components#118]
Currently, the Job Manager app allows users to access the application with a unified set of credentials. This feature should extend SSO functionality to all other apps.

## Checklist

- [x] Store Fulfillment
- [x] BOPIS Fulfillment
- [x] Pre-order Management
- [x] Receiving
- [x] Inventory Cycle Count
- [x] Import
- [x] Threshold Management
- [x] Picking

**Comment by ymaheshwari1** [comment]
Closing as completed
