### ISSUE TITLE
 Implement Centralized App Settings Page

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/dxp-components#136]
This feature aims to provide users with a single, user-friendly interface where they can configure and customize various aspects of the application to suit their preferences and requirements. Develop a centralized App Settings Page component that can be seamlessly integrated into different apps. This component should be designed to work cohesively with various DXP elements.

**Comment by dt2patel** [comment]
closing this task since we are instead making individual cards and settings that can actually be implemented in any screen
