### ISSUE TITLE
 Implement Centralized Timezone Configuration

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/dxp-components#139]
This feature aims to provide users with a method for configuring timezones across the applications, ensuring that time-sensitive data is accurately displayed and managed. We will develop a dedicated Timezone Configuration component that serves as a central hub for users to configure their timezone settings. This component should be accessible from any relevant part of the application.

**Comment by Adameddy26** [comment]
Verified the changes and are working fine. 
Hence, closing this ticket.
