### ISSUE TITLE
Implement Centralized Language Switcher

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/dxp-components#141]
This feature aims to provide users with a unified and efficient method for selecting their preferred language within the application, ensuring that content is presented in a language they understand. Develop a dedicated Language Switcher component that serves as a central hub for users to change the language of the application. This component should be accessible from any relevant part of the application.

**Comment by ymaheshwari1** [comment]
PR for some reference: https://github.com/hotwax/dxp-components/pull/109
