### ISSUE TITLE
Implement Centralized Sign-Out for All Applications

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/dxp-components#144]
To enhance security and user convenience, we propose the implementation of a centralized sign-out feature that allows users to log out from all connected applications simultaneously. This feature aims to provide users with an efficient way to ensure that their sessions are terminated across all associated applications, reducing the risk of unauthorized access.

**Comment by Dhiraj1405** [comment]
- [ ] Fulfilment
- [ ] Picking
- [ ] Import
- [ ] Cycle Count
- [ ] BOPIS

**Comment by ymaheshwari1** [comment]
Closing as completed.
