### ISSUE TITLE
Implement OMS Instance Navigation Component in Apps

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/dxp-components#177]
Refer this issue #140 

As the component is now moved to a centralised place, we should start implementing it in the apps: 

- [x] **Pre-order Management**
- [x] **BOPIS**
- [x] **Store Fulfilment**
- [x] **Picking**
- [x] **Job Manager**
- [x] **Threshold Management**
- [x] **Receiving**
- [x] **Import**
- [x] **Cycle Count**

**Comment by ymaheshwari1** [comment]
Closing as implemented in all apps
