### ISSUE TITLE
Time Zone Selector Should Display User's Current Time for Clarity

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/dxp-components#221]
**Problem:**
When users select a time zone, it can be confusing due to factors like daylight savings time. Currently, the time zone selector does not provide real-time feedback to users about their current time in the selected time zone. This lack of information can lead to confusion and incorrect selections, especially during transitions to and from daylight savings time.

**Proposed Solution:**
Implement a feature in the time zone selector that displays the current time for the selected time zone. This real-time feedback will help users confirm whether they have selected the correct time zone, making the process more intuitive and reducing the potential for errors.

**Comment by Dhiraj1405** [comment]
https://www.figma.com/file/j3l0F2DioUHEuQT53NOQJY/Ionic-6-Material-UI-Kit-(Community)-(Nidhi--2023)?type=design&node-id=26091%3A64216&mode=design&t=a7snZAj0I6KxRGX9-1

**Comment by ymaheshwari1** [comment]
This will be handled in https://github.com/hotwax/dxp-components/issues/262.
@Dhiraj1405 please check if the above feature request handles this case, if yes please close this issue.

**Comment by Dhiraj1405** [comment]
> This will be handled in #262. @Dhiraj1405 please check if the above feature request handles this case, if yes please close this issue.

Yes @ymaheshwari1 This handles the requirement, should I close this ticket?

**Comment by ymaheshwari1** [comment]
> > This will be handled in #262. @Dhiraj1405 please check if the above feature request handles this case, if yes please close this issue.
> 
> Yes @ymaheshwari1 This handles the requirement, should I close this ticket?

Sure
