### ISSUE TITLE
Implement User Preference Saving for Last Selected Shop in Quick Switcher

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/dxp-components#242]
Currently, the Quick Switcher does not save the user's last selected shop, leading to inconvenience for users who frequently switch between shops. This enhancement aims to improve the user experience by implementing a feature that saves the user's preference for the last selected shop in the Quick Switcher.

**Comment by dt2patel** [comment]
closing this issue since we are now giving favorites section in user app.
