### ISSUE TITLE
Fix permission issue when defining a base permission for app

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/dxp-components#254]
Reference PR:
https://github.com/hotwax/receiving/pull/293/files#diff-d3c10a6ece79180d52468851ebe745d66365adafc59ee774a50b5687b3d42ff6L46

Check in all apps where we have support for base permission, and refer the above PR to fix base permission logic.

**Comment by Adameddy26** [comment]
Verified and working fine. Hence, closing it.
