### ISSUE TITLE
Fix error handling in login process

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/dxp-components#258]
Currently, most of the OMS APIs return an error object in case of failure. However, the error is treated as a string in error handling. Please enhance the error handling to consider both the error pattern so that messages like [object, object] can be avoided.
![Screenshot from 2024-02-06 11-08-25](https://github.com/hotwax/dxp-components/assets/40700208/1a2fec17-2b24-42c1-b02b-cc62b3421dd2)

**Comment by Adameddy26** [comment]
Issue verified in v2.0.3 and found that issue is not fixed properly.

![Screenshot 2024-03-13 at 4 42 29 PM](https://github.com/hotwax/dxp-components/assets/158989293/fa6c4ec5-4044-4d58-97d4-50fa3085c44f)

**Comment by Adameddy26** [comment]
Verified this issue for import app release v2.15.0 and found that issue is working fine.
![Uploading Screenshot 2024-03-19 at 4.45.13 PM.png…]()

**Comment by Adameddy26** [comment]
Issue verified and working fine in facilities app release v1.5.0.
