### ISSUE TITLE
Fix loader not dismissing in case of login failure

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/dxp-components#259]
## Current behavior

Loader not getting dismissed in case of login failure when any api throws an error.

## Expected behavior

Loader should be dismissed after the execution of api whether it fails or success.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by ravilodhi** [comment]
@Adameddy26 Please check whether this issue still persists.

**Comment by Adameddy26** [comment]
Verified and working fine. Hence, closing this ticket.
