### ISSUE TITLE
Updating `Timezone` DXP components in all apps

### ISSUE THREAD

**Issue by sanjanashrivastava** [hotwax/dxp-components#262]
The current `Timezone` component available on the settings page of all the apps is very simplified. We need an enhanced DXP component where Browser Timezone and Selected Timezone both are visible along with the current time. Browser timezone also needs to be displayed in the Select time zone popup. Attaching screenshots of the expected component, and it can examined in detail in the HC Ionic Figma file as well. 

This needs to be done in all the apps. 

<img width="534" alt="Select time zone" src="https://github.com/hotwax/dxp-components/assets/155512107/1d9e79f3-7f78-4fdd-af18-8f3d7dd21e89">
<img width="436" alt="Timezone " src="https://github.com/hotwax/dxp-components/assets/155512107/90416ea6-47f4-4317-ba4d-c9546071ea9c">

https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?type=design&node-id=29987%3A18244&mode=design&t=Q0x3xJ1ZVorTXD1k-1

**Comment by ymaheshwari1** [comment]
Create a PR for using this change in all apps @R-Sourabh.

**Comment by Adameddy26** [comment]
Issue verified and working fine in Import App release 2.16.0.
https://jam.dev/c/a8d81d2f-0e28-4420-a992-818689d8a01e

**Comment by Adameddy26** [comment]
Enhancement verified and working fine in Users App release v1.8.0.
https://jam.dev/c/e8652ba4-49bb-45aa-9bf7-90e62d272c98

**Comment by Adameddy26** [comment]
Enhancement verified and working fine in Receiving App release v2.26.0
https://jam.dev/c/9913aca2-be30-4579-9b7a-0b06a8847165

**Comment by Adameddy26** [comment]
Enhancement verified and working fine in Facilities App release v1.6.0.
https://jam.dev/c/44f9c12c-6bf0-4348-aa35-a3b7a656b963

**Comment by Adameddy26** [comment]
Enhancement verified and working fine in Job Manager App release v2.22.0.
https://jam.dev/c/38ffaef0-906e-4582-9991-9198980b48b2

**Comment by Adameddy26** [comment]
Enhancement verified and working fine in Fulfillment App release v2.2.0.
https://jam.dev/c/7bb09ffa-1e8b-4589-bdb9-e2667e987b32
