### ISSUE TITLE
Update oms-api package to latest release

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/dxp-components#272]
## What is the motivation for adding/enhancing this feature?

Update the oms-api package in all apps to latest release.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified and working fine in facilities app release v1.5.0.

**Comment by Adameddy26** [comment]
Verified and working fine in user management app release v1.7.0.

**Comment by Adameddy26** [comment]
Verified and working fine in BOPIS app release v2.22.0.
