### ISSUE TITLE
Failed to move to commerce when clicking `Go To OMS` when having oms url in specific pattern

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/dxp-components#275]
## Current behavior

When clicking `Go To OMS`, the user does not move to the commerce

## Expected behavior

The redirection to commerce should always happen to have a consistent user experience

## Steps to reproduce the issue

1. Go to commerce
2. Click on `Go To Lauunchpad`
3. Once logged-in into the launchpad, click the redirect icon next to oms name
4. Verify that the commerce does not open

This can also regenerate when login into launchpad using oms value as `https://<oms>.hotwax.io`

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by ymaheshwari1** [comment]
Update Dxp package version in all apps.

**Comment by Adameddy26** [comment]
Verified and working fine in facilities app release v1.5.0.
