### ISSUE TITLE
Selected Timezone radio button not appearing checked when user opens Time Zone modal in any App.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/dxp-components#281]
## Expected behavior
When a user selects a time zone within the time zone modal, the corresponding radio button should be visually indicated as checked, providing clear feedback to the user regarding the currently selected time zone.

## Steps to reproduce the issue
Open any app that contains a time zone modal or setting.
Navigate to the time zone settings or modal within the app.
Observe the list of available time zones and the radio buttons next to each option.
Notice that although a time zone is selected, the corresponding radio button does not appear visually checked.

## Additional information
https://jam.dev/c/85126e30-b81f-4bf1-8fcd-ad2d6656b0af

**Comment by ymaheshwari1** [comment]
This will be fixed in https://github.com/hotwax/dxp-components/pull/283

**Comment by ravilodhi** [comment]
@Adameddy26 Please check if we can close this.

**Comment by Adameddy26** [comment]
Verified and working fine. Hence, closing this ticket.
