### ISSUE TITLE
Improve Launchpad Instance Management

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/dxp-components#287]
## Problem
Users can open the Launchpad in multiple tabs with different Order Management System (OMS) instances, causing confusion about session consistency and instance association.

## Enhancement Proposal
Improve Launchpad instance management to ensure session consistency and prevent confusion.

## Additional information
https://jam.dev/c/b946f13b-4605-4099-8c44-e7c6f59923a4

**Comment by Dhiraj1405** [comment]
@Adameddy26 Not sure about the customer use case here.

**Comment by Dhiraj1405** [comment]
Closing as there is no specific use case
