### ISSUE TITLE
Infinite scroll issue when used with search bar

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/dxp-components#289]
## Current behavior
Infinite scrolling is not working with search bar after the upgrade to ionic 7.

## Expected behavior 
Check all the apps where infinite scrolling is used. Infinite scrolling should work correctly.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by ravilodhi** [comment]
Take reference of this fix - https://github.com/hotwax/users/pull/206

**Comment by Adameddy26** [comment]
When performing a search on the users page and clicking on a search result to view the user's profile, navigating back to the previous page results in the inability to scroll down the search results.

This issue is found in users app but need to be fixed in all apps wherever this functionality exists.

**Comment by ymaheshwari1** [comment]
Refer to this PR with latest fix:
https://github.com/hotwax/users/pull/213

**Comment by Adameddy26** [comment]
Verified and working fine in facilities app release v1.6.1. 
https://jam.dev/c/7ce45f60-d381-416c-8f6b-125161e1dd90

**Comment by Adameddy26** [comment]
Verified and working fine in fulfillment app release v2.3.0. 
https://jam.dev/c/14e8852b-aa0b-4359-b809-85d6ac27ab6f

**Comment by Adameddy26** [comment]
Verified and working fine in job-manager app release v2.23.0.

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v1.18.1 of pre-order app.
