### ISSUE TITLE
Error page appears instead of OMS login page on re-clicking 'Go to OMS' link after logout

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/dxp-components#292]
## Expected behavior
After logging out from the OMS, clicking the 'Go to OMS' link should redirect the user to the OMS login page to authenticate again.

## Steps to reproduce the issue
Log in to the application(any).
Open the settings page.
Click the 'Go to OMS' link, which opens the OMS link in a new tab.
Log out from the OMS tab.
Return to the application and click the 'Go to OMS' link again.
Observe the issue.

## Additional information
https://jam.dev/c/c3fd8c33-fb40-453f-a3f7-29ea07ab6922

**Comment by ymaheshwari1** [comment]
Closing as will be handled on oms side.
