### ISSUE TITLE
Default to First Segment on Facility Change Within a Tab

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/dxp-components#317]
## Note 
**Currently this behavior is observed for the BOPIS  and Inventory count App.**

## Description:
To improve the user experience, it is proposed that when redirecting to the same tab after opening any segment (except the first one) and then changing the facility from another tab in the tab bar, the first segment should be selected by default instead of the previously selected segment. This ensures consistency and predictability in navigation.

## Current Behavior:
When a user navigates to a tab with multiple segments and selects a segment other than the first one, changing the facility from another tab retains the previously selected segment upon redirection.

## Additional Information 
https://jam.dev/c/d743901b-a956-42e0-9cf8-d3c89a6f39cc

**Comment by Dhiraj1405** [comment]
Closing as not required
