### ISSUE TITLE
Add base permissions for all the apps

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/dxp-components#323]
## What is the motivation for adding/enhancing this feature?
Adding the base permission will give us control to manage access to apps. For example store manage/associate don't be allowed to access users app etc.

## What are the acceptance criteria?
User with the respective base permission should be able to access that app.
Below are the base permissions for each app -

BOPIS - BOPIS_APP_VIEW
Fulfillment - FULFILLMENT_APP_VIEW
Pre-Orders - PREORDER_APP_VIEW
Available to Promise - ATP_APP_VIEW
Job Manager - JOB_MANAGER_APP_VIEW
Order Routing - ORDER_ROUTING_APP_VIEW
Receiving - RECEIVING_APP_VIEW
Cycle Count - INVCOUNT_APP_VIEW
Picking - PICKING_APP_VIEW
Import - IMPORT_APP_VIEW
Users - USERS_APP_VIEW
Facilities - FACILITIES_APP_VIEW
Company - COMPANY_APP_VIEW

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by R-Sourabh** [comment]
Because `Picking` is a low priority, we will add the base permission later.

**Comment by Adameddy26** [comment]
Verified and working fine in all apps. Hence, closing this ticket.

**Comment by ymaheshwari1** [comment]
@Adameddy26 Close this issue as completed if everything looks good to you.

**Comment by Adameddy26** [comment]
Verified and working fine for picking app on launchpad production. Hence, closing this ticket.
