### ISSUE TITLE
Update the usage of i18n library

### ISSUE THREAD

**Issue by disha1202** [hotwax/dxp-components#72]
Check if we can directly use the i18n library in .ts files and remove translate method.

**Comment by sanskar345** [comment]
### When installing the latest version of vue-i18n (9.4.0) in the app getting this error - 

```
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file

|     if (shared.isString(source)) ;
|     else {
>         if (source.loc?.source) {
|             return source.loc.source;
|         }
```

Unable to find anything for resolving this error.
Tried changing babel config and configuring webpack in vue config for this file but nothing working.

_Refer to this - https://github.com/intlify/vue-i18n-next/issues/1526_

### We can shift to vue-i18n 9.2.2 stable release.

In this V9.2.2 got type error with i18n messages option which can be resolved by giving type I18nOptions['messages'].

Like below :-

`const messages: I18nOptions['messages'] = {}.`

**Comment by ymaheshwari1** [comment]
For now we will not update the i18n to latest releases and will use the latest stable release instead.
Handled the implementation in https://github.com/hotwax/dxp-components/pull/173
