### ISSUE TITLE
Inconsistent favicon sizes across applications

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/dxp-components#96]
## What is the motivation for adding/enhancing this feature?
The current state of favicons in applications exhibits irregular sizes, which leads to an inconsistent user experience. 

## What are the acceptance criteria?
1. Favicons should be of uniform size across all applications.
2. The recommended favicon size is 16x16 pixels.
3. Favicons should maintain their aspect ratio when scaled, to prevent distortion or stretching.
4. Favicons should be replaced in the following apps
<ul>
  <li> Job Manager
  <li> Pre-order Management
  <li> BOPIS Fulfillment
  <li> Inventory count
  <li> Import
  <li> Receiving
  <li> Threshold management
  <li> Picking
</ul>

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

## Additional information

**Comment by dt2patel** [comment]
completed under separate issues in each app
